=== giellalt/dict-fin-nob/scripts/dict_finnob.dtd
<!ELEMENT e ( lg, mg+ ) >
<!ATTLIST e reverse NMTOKEN #IMPLIED >
<!ATTLIST e src CDATA #IMPLIED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos ( A | Abbr | Adv | CC | CS | Clt | Interj | 
                  N | Num | Pcle | Po | Pr | Pron | Qu | V ) #REQUIRED >
<!ATTLIST l src NMTOKEN #IMPLIED >
<!ATTLIST l val ( IV | TV ) #IMPLIED >
<!ATTLIST l type (Prop) #IMPLIED >

<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT lg ( l ) >

<!ELEMENT mg ( tg ) >

<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xml:lang (fin) #IMPLIED>
<!ATTLIST r id (finnob) #IMPLIED>

<!ELEMENT stem ( #PCDATA ) >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t gen ( f | m | n ) #IMPLIED >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t pos ( A | Adv | CC | CS | Cp | Det | Interj | 
                  N | Num | Po | Pr | Pron | V ) #REQUIRED >
<!ATTLIST t t_type NMTOKEN #IMPLIED >
<!ATTLIST t type ( Prop ) #IMPLIED >

<!ELEMENT tg ( syng | t | xg )* >
<!ATTLIST tg comment CDATA #IMPLIED >
<!ATTLIST tg re CDATA #IMPLIED >
<!ATTLIST tg xml:lang ( nob ) #IMPLIED >

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

=== giellalt/dict-fin-nob/src/CC_finnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet title="Dictionary view" media="screen,tv,projection" href="../../scripts/gt_dictionary.css" type="text/css"?>
<?xml-stylesheet alternate="yes" title="Hierarchical view" media="screen,tv,projection" href="../../scripts/gt_dictionary_alt.css" type="text/css"?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../scripts/dict_finnob.dtd">
<r id="finnob" xml:lang="fin">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT
          and members of the language community. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="CC">kun</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">da</t>
            <t pos="CC">når</t>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">enn</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">jos</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">hvis</t>
            <t pos="CC">om</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">eli</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">ja</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">samt</t>
            <t pos="CC">og</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">joko ... tai</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">enten ... eller</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">mutta</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">men</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">tai</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">tai</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">vai</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">vaikka</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">selv om</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CC">vain</l>
      </lg>
      <mg>
         <tg xml:lang="nob" re="i spørsmål">
            <t pos="CC">eller</t>
         </tg>
      </mg>
   </e>
</r>
